---

name: Pylint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install flake8 pylint
      - name: Analysing the code with flake8
        run: |
          flake8 `git ls-files '*.py'`
      - name: Analysing the code with pylint
        run: |
          pylint `git ls-files '*.py'`
